<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('user_restrictions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('user_id')->references('id')->on('users')->cascadeOnDelete();
            $table->enum('type', ['allergy','intolerance','injury','preference','medical_restriction']);
            $table->text('description')->comment('Free text (can be generated by AI)');
            $table->enum('severity', ['mild','moderate','severe'])->default('moderate');
            $table->foreignUuid('food_id')->nullable()->references('id')->on('foods')->nullOnDelete();
            $table->foreignUuid('exercise_id')->nullable()->references('id')->on('exercises')->nullOnDelete();
            $table->enum('origin', ['user','ai','doctor'])->default('user');
            $table->boolean('is_active')->default(true);
            $table->timestamps();

            $table->index(['user_id', 'is_active']);
        });

        Schema::create('body_measurements', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('user_id')->references('id')->on('users')->cascadeOnDelete();
            $table->date('date');
            $table->decimal('weight_kg', 5, 2);
            $table->decimal('body_fat_pct', 4, 1)->nullable();
            $table->decimal('muscle_mass_kg', 5, 2)->nullable();
            $table->decimal('waist_circumference_cm', 5, 2)->nullable();
            $table->decimal('hip_circumference_cm', 5, 2)->nullable();
            $table->decimal('arm_circumference_cm', 5, 2)->nullable();
            $table->decimal('bmi', 4, 2)->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->unique(['user_id', 'date']);
            $table->index(['user_id', 'date']);
        });

        Schema::create('water_logs', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('user_id')->references('id')->on('users')->cascadeOnDelete();
            $table->date('date');
            $table->decimal('liters', 4, 2);
            $table->time('time')->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->index(['user_id', 'date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('water_logs');
        Schema::dropIfExists('body_measurements');
        Schema::dropIfExists('user_restrictions');
    }
};
